# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e856d82e2a55778cc8609519856b03866a3c8a515e2e6cba4cb9a595e606170fe7e7518d0946477529246f965450eae975c388f79bfa7bec0cd471eda2546667

test:
  secret_key_base: 646e266be9570c72a005a1789cdea64c7a917a67dd608581a71b2641396a64b8411c72d1c4f1000fbe78dc688d52dc7d7b47628cb7bd87b8ba55103cf84a5ae9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
